#!/bin/bash

file="$1"
dict=(
    "rflags рфлаги"
    "eflags ефлаги"
    "flags флаги"
    "callf зовф"
    "r15d р15ч"
    "r14d р14ч"
    "r13d р13ч"
    "r12d р12ч"
    "r11d р11ч"
    "r10d р10ч"
    "r15d е15"
    "r14d е14"
    "r13d е13"
    "r12d е12"
    "r11d е11"
    "r10d е10"
    "r15w р15д"
    "r14w р14д"
    "r13w р13д"
    "r12w р12д"
    "r11w р11д"
    "r10w р10д"
    "r15w д15"
    "r14w д14"
    "r13w д13"
    "r12w д12"
    "r11w д11"
    "r10w д10"
    "r15b р15б"
    "r14b р14б"
    "r13b р13б"
    "r12b р12б"
    "r11b р11б"
    "r10b р10б"
    "r15b б15"
    "r14b б14"
    "r13b дб3"
    "r12b б12"
    "r11b б11"
    "r10b б10"
    "ldtr лдтр"
    "test проб"
    "imul зумн"
    "retf воздф"
    "jmpf идтиф"
    "push толк"
    "call зов"
    "rip рип"
    "r15 р15"
    "r14 р14"
    "r13 р13"
    "r12 р12"
    "r11 р11"
    "r10 р10"
    "rsp рсп"
    "rbp рбп"
    "rdi рди"
    "rsi рси"
    "rdx рдх"
    "rcx рсх"
    "rbx рбх"
    "rax рах"
    "eip еип"
    "r9d р9ч"
    "r8d р8ч"
    "r9d е9"
    "r8d е8"
    "esp есп"
    "ebp ебп"
    "edi еди"
    "esi еси"
    "edx едх"
    "ecx есх"
    "ebx ебх"
    "eax еах"
    "r9w р9д"
    "r8w р8д"
    "r9w д9"
    "r8w д8"
    "r9b р9б"
    "r8b р8б"
    "r9b б9"
    "r8b б8"
    "sbb минсп"
    "adc плюсс"
    "xor искл"
    "and и"
    "cmp срав"
    "sub минс"
    "add плюс"
    "mov быть"
    "jle иднб"
    "jle идмр"
    "jnl идбр"
    "jnl иднм"
    "jnp иднч"
    "jnp иднч"
    "jns иднз"
    "jbe иднв"
    "jbe идпр"
    "jne иднр"
    "jne идн0"
    "jnb иднс"
    "jnb идвр"
    "jnb иднп"
    "jno идни"
    "ret возд"
    "dec умнш"
    "inc увлч"
    "pop выт"
    "int прер"
    "jmp идти"
    "r9 р9"
    "r8 р8"
    "ip ип"
    "di ди"
    "si си"
    "bp бп"
    "sp сп"
    "bx бх"
    "dx дх"
    "cx сх"
    "ax ах"
    "bl бл"
    "cl сл"
    "dl дл"
    "al ал"
    "bh бг"
    "ch сг"
    "dh дг"
    "ah аг"
    "tr тр"
    "gs гс"
    "fs фс"
    "ss сс"
    "es ес"
    "ds дс"
    "cs кс"
    "or или"
    "jg идб"
    "jg иднмр"
    "jl иднбр"
    "jl идмр"
    "jp идчр"
    "jp идч"
    "js идз"
    "ja идв"
    "ja иднпр"
    "je идр"
    "je ид0"
    "jb идс"
    "jb иднвр"
    "jb идп"
    "jo иди"
)

wass=0
wasn0=0

for pair in "${dict[@]}"; do
	read -r old new <<< "$pair"
	was=$(grep -o "$old" "$file" | wc -l)
	sed -i "s/$old/$new/g" $file

	if [ "$was" -gt 0 ]; then
		echo -e "$old\t->\t$new\t$was раз"
		wass=$((wass + was))
		wasn0=$((wasn0 + 1))
	fi
done

echo -e "слов заменено: $wasn0 раз, замен всего: $wass"
