#!/bin/bash

file="$1"
dict=(
    "executable исп"
    "writeable изм"
    "writable изм"
    "readable чит"
    "syscall сзов"
    "segment участок"
    "eflags ефлаги"
    "rflags рфлаги"
    "qword вбайт"
    "dword чбайт"
    "entry вход"
    "callf зовф"
    "flags флаги"
    "word дбайт"
    "byte байт"
    "lock атом"
    "jnae иднвр"
    "jnbe иднпр"
    "jnge иднбр"
    "jnle иднмр"
    "call зов"
    "push толк"
    "jmpf идтиф"
    "retf воздф"
    "imul зумн"
    "test проб"
    "ldtr лдтр"
    "r10b б10"
    "r11b б11"
    "r12b б12"
    "r13b дб3"
    "r14b б14"
    "r15b б15"
    "r10b р10б"
    "r11b р11б"
    "r12b р12б"
    "r13b р13б"
    "r14b р14б"
    "r15b р15б"
    "r10w д10"
    "r11w д11"
    "r12w д12"
    "r13w д13"
    "r14w д14"
    "r15w д15"
    "r10w р10д"
    "r11w р11д"
    "r12w р12д"
    "r13w р13д"
    "r14w р14д"
    "r15w р15д"
    "r10d е10"
    "r11d е11"
    "r12d е12"
    "r13d е13"
    "r14d е14"
    "r15d е15"
    "r10d р10ч"
    "r11d р11ч"
    "r12d р12ч"
    "r13d р13ч"
    "r14d р14ч"
    "r15d р15ч"
    "nop ыыы"
    "jpe идчр"
    "jle идмр"
    "jmp идти"
    "int прер"
    "pop выт"
    "inc увлч"
    "dec умнш"
    "ret возд"
    "jno идни"
    "jnb иднп"
    "jae идвр"
    "jnc иднс"
    "jnz идн0"
    "jne иднр"
    "jbe идпр"
    "jna иднв"
    "jns иднз"
    "jnp иднч"
    "jpo иднч"
    "jnl иднм"
    "jge идбр"
    "jle идмр"
    "jng иднб"
    "mov быть"
    "add плюс"
    "sub минс"
    "cmp срав"
    "and и"
    "xor искл"
    "adc плюсс"
    "sbb минсп"
    "r8b б8"
    "r9b б9"
    "r8b р8б"
    "r9b р9б"
    "r8w д8"
    "r9w д9"
    "r8w р8д"
    "r9w р9д"
    "eax еах"
    "ebx ебх"
    "ecx есх"
    "edx едх"
    "esi еси"
    "edi еди"
    "ebp ебп"
    "esp есп"
    "r8d е8"
    "r9d е9"
    "r8d р8ч"
    "r9d р9ч"
    "eip еип"
    "rax рах"
    "rbx рбх"
    "rcx рсх"
    "rdx рдх"
    "rsi рси"
    "rdi рди"
    "rbp рбп"
    "rsp рсп"
    "r10 р10"
    "r11 р11"
    "r12 р12"
    "r13 р13"
    "r14 р14"
    "r15 р15"
    "rip рип"
    "jo иди"
    "jb идп"
    "jc идс"
    "jz ид0"
    "je идр"
    "ja идв"
    "js идз"
    "jp идч"
    "jg идб"
    "or или"
    "cs кс"
    "ds дс"
    "es ес"
    "ss сс"
    "fs фс"
    "gs гс"
    "tr тр"
    "ah аг"
    "dh дг"
    "ch сг"
    "bh бг"
    "al ал"
    "dl дл"
    "cl сл"
    "bl бл"
    "ax ах"
    "cx сх"
    "dx дх"
    "bx бх"
    "sp сп"
    "bp бп"
    "si си"
    "di ди"
    "ip ип"
    "r8 р8"
    "r9 р9"
)

wass=0
wasn0=0

for pair in "${dict[@]}"; do
	read -r old new <<< "$pair"
	was=$(grep -o "$old" "$file" | wc -l)
	sed -i "s/$old/$new/g" $file

	if [ "$was" -gt 0 ]; then
		echo -e "$old\t->\t$new\t$was раз"
		wass=$((wass + was))
		wasn0=$((wasn0 + 1))
	fi
done

echo -e "слов заменено: $wasn0 раз, замен всего: $wass"
